# Generated by Django 5.2.17 on 2026-10-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0007_alter_redirect_create_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the object was last updated.",
                verbose_name="Update time",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the object was created.",
                verbose_name="Creation time",
            ),
        ),
        migrations.AlterField(
            model_name="redirect",
            name="create_method",
            field=models.CharField(
                choices=[
                    ("API", "API"),
                    ("WEB", "Web"),
                    ("WEB+FILE", "Web (file)"),
                ],
                default="WEB",
                help_text="method_which_redirect_was_created",
                max_length=20,
                verbose_name="create_method",
            ),
        ),
    ]
