# Generated by Django 5.2.17 on 2026-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0007_alter_click_browser_alter_click_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="click",
            options={"verbose_name": "click", "verbose_name_plural": "clicks"},
        ),
        migrations.RenameField(
            model_name="click",
            old_name="clicked_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="click",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the object was last updated.",
                verbose_name="Update time",
            ),
        ),
        migrations.AlterField(
            model_name="click",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the object was created.",
                verbose_name="Creation time",
            ),
        ),
    ]
