# Generated by Django 5.2.17 on 2026-10-06 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_blockeddomain_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockeddomain",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the object was created.",
                verbose_name="Creation time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blockeddomain",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the object was last updated.",
                verbose_name="Update time",
            ),
        ),
    ]
